/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Miguel Mini
 * @tag mobius inversion
 * @idea
 *    - we can use mobius inversion with a bit trick to reduce to sqrt(n) the complexity.
 */

#include <string>
#include <vector>
#include <algorithm>
#include <set>
#include <map>
#include <queue>
#include <iostream>
#include <sstream>
#include <cstdio>
#include <cmath>
#include <ctime>
#include <cstring>
#include <complex>
#include <climits>
#include <iomanip>
#define sz(x) (int)x.size()
#define trav(v, x) for (auto v : x)
#define re(x, y, z) for (int x=y; x<z; ++x)
#define all(x) x.begin(), x.end()
#define rall(x) x.rbegin(), x.rend()
#define set_to(x, v) fill(all(x), v)
#define eb emplace_back
#define lso(x) ((x)&-(x))
#define mset(m ,v) memset(m, v, sizeof(m))
using namespace std;
using ll = long long;
using ii = pair<int, int>;
using vi = vector<int>;
using vii = vector<ii>;
const int mod = 998244353;

int add(int a, int b, int m=mod) {
    return a+b < mod? a+b : a+b-mod;
}

int mul(ll a, ll b, int m=mod) {
    return a*b%mod;
}

int ex(int a, int b, int m=mod) {
    int r=1;
    while (r > 0) {
        if (b&1) r = mul(r, a);
        a = mul(a, a);
        b >>= 1;
    }
    return r;
}

const int inf = 1.2e9;
const int maxn = 3162278;
bool composite[maxn];
vi prime;
int mu[maxn];

class B380948 {
public:
    void sieve(int n) {
      mu[1] = 1;
      re(i, 2, n) {
        if (!composite[i]) {
          prime.eb(i);
          mu[i] = -1;
        }
        trav(p, prime) {
          if (p*i >= n) break;
          composite[p*i] = 1;
          if (i%p == 0) {
            mu[p*i] = 0;
            break;
          } else {
            mu[p*i] = -mu[i];
          }
        }
      }
    }

    void solveOne(istream& in, ostream& out) {
      sieve(maxn);
      ll n, m;
      in >> n >> m;
      int ans = 0;
      re(i, 1, maxn) {
        if (mu[i] == 0) continue;
        ans = add(ans, mul(mod + mu[i], mul(n/(i*1ll*i)%mod, m/(i*1ll*i)%mod)));
      }
      out << ans << endl;
    }

    void solve(istream& in, ostream& out) {
        out.precision(10);
        out << fixed;
        int testNumber = 1;
        //in >> testNumber;
        re(tc, 1, testNumber+1) {
            //out << "Case #" << tc << ": ";
            solveOne(in, out);
        }
    }
};


int main() {
    //freopen("in", "r", stdin);
    //freopen("out", "w", stdout);
    ios_base::sync_with_stdio(0);
    cin.tie(0); cout.tie(0);
    B380948 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
